### ISSUE TITLE
CORS header missing

### ISSUE THREAD

**Issue by SchniderB** [mandarsd/pdb-sequence-viewer#1]
Hello,

Our platform has been using the PDBe sequence viewer for multiple years and it appears to have stopped working at some point.

The window of the viewer shows the message "Downloading API data...". Upon clicking on one of the buttons "Compact" or "Expanded", the message will change to "Error downloading API data!". When examining the console, one can see that the typical CORS-header-missing errors are raised:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.ebi.ac.uk/pdbe/api/pdb/entry/observed_residues_ratio/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.ebi.ac.uk/pdbe/api/pdb/entry/observed_residues_ratio/. (Reason: CORS request did not succeed). Status code: (null).
```

I have updated the files `pdb.sequence.viewer.min.css` and `pdb.sequence.viewer.min.js` just in case, but it did not fix the issue.

Is it now necessary to request the access to PDBe sequence viewer's resource ?

Thank you in advance for your help!
Best regards,
Boris

**Comment by mandarsd** [comment]
Hello Boris,
PDBe sequence viewer is no longer developed and maintained since it was replaced by ProtVista PDB long back.
You could refer to the ProtVista documentation should you want to switch to it - https://github.com/PDBeurope/protvista-pdb

**Comment by mandarsd** [comment]
I've fixed the CORS issue. You could pull the updated files in your application.

**Comment by SchniderB** [comment]
Hello Mandar,

Thank you for your help and suggestion.

Pulling the changes in the file `pdb.sequence.viewer.min.js` has solved the CORS issue. We will consider switching to ProtVista PDB at some point.

Best regards,
Boris
